title: Preethi Sakleshpura Manjunatha
logo: IMG-20250302-WA0009.jpg
theme: jekyll-theme-minimal

<html lang="en">
  <header>
    <p>Quality Assurance Tester (Manual and Automation)</p>
    <p>Banbury, United Kingdom</p>
    <p><a href="tel:+447868061116">+44 07868 061116</a> | <a href="mailto:preethism22@gmail.com">preethism22@gmail.com</a></p>
    <p><a href="https://www.linkedin.com/in/preethi-sakaleshpura-manjunatha-7bb494288" target="_blank">LinkedIn Profile</a></p>
  </header>
  </html>
